### ISSUE TITLE
wg0 interface missing 

### ISSUE THREAD

**Issue by tonyaldo1** [SirToffski/WireGuard-Ligase#3]
Hi
I run through the quick setup guide 100% successfully on Ubuntu 18.04 LTS (Lightsail) and reboot
Once the machine is back up, I do not see the interface wg0

**Comment by SirToffski** [comment]
Hey, I'll take a look at the code. This sounds like a `systemd` service issue, for whatever reason it was not enabled. Will get back soon.

**Comment by SirToffski** [comment]
Hey, this should also be resolved now. It was my fault in being sloppy with server config and `PostUp` / `PostDown` IPTABLES. There was a syntax error which I had fixed in the advanced setup script some time ago, but must have forgotten to do the same with this one.

The issue was a missing `-o` between `POSTROUTING` and `eth0` (or whatever your local iface is).

Here's how the error showed up:
```
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.10.100.1 dev wg0
[#] ip link set mtu 8921 up dev wg0
[#] ip -4 route add 10.10.100.13/32 dev wg0
[#] ip -4 route add 10.10.100.12/32 dev wg0
[#] ip -4 route add 10.10.100.11/32 dev wg0
[#] ip -4 route add 10.10.100.10/32 dev wg0
[#] iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING eth0 -j MASQUERADE; ip6tables -A FORWARD -i wg0 -j ACCEPT; ip6tables -t nat -A POSTROUTING eth0 -j MASQUERADE
Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
[#] ip link delete dev wg0
```

The `Bad argument eth0'` line was a giveway - Im surprised it even worked before rebooting since in theory the `wg0` interface should have never come up because of this. Anyhow the corrected version looks like this:

```
Server PostUp: iptables -A FORWARD -i wg1 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE; ip6tables -A FORWARD -i wg1 -j ACCEPT; ip6tables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
Server PostDown: iptables -D FORWARD -i wg1 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE; ip6tables -D FORWARD -i wg1 -j ACCEPT; ip6tables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
```

And the resulting output is what we would want to see:
```
mode of '/etc/wireguard/wg1.conf' changed from 0644 (rw-r--r--) to 0600 (rw-------)
[#] ip link add wg1 type wireguard
[#] wg setconf wg1 /dev/fd/63
[#] ip -4 address add 10.100.100.1 dev wg1
[#] ip link set mtu 8921 up dev wg1
[#] ip -4 route add 10.100.100.13/32 dev wg1
[#] ip -4 route add 10.100.100.12/32 dev wg1
[#] ip -4 route add 10.100.100.11/32 dev wg1
[#] ip -4 route add 10.100.100.10/32 dev wg1
[#] iptables -A FORWARD -i wg1 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE; ip6tables -A FORWARD -i wg1 -j ACCEPT; ip6tables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
Created symlink /etc/systemd/system/multi-user.target.wants/wg-quick@wg1.service → /lib/systemd/system/wg-quick@.service.
```

Thanks for reporting!! Let me know how it goes.


PS. This gave me an idea to set up some exit codes and exit messages in critical parts of the script for easier debugging :)
