### ISSUE TITLE
Clients only

### ISSUE THREAD

**Issue by ghost** [SirToffski/WireGuard-Ligase#6]
there are a couple of problems when adding a new user, nothing is automated..

when generating new clients # 3, is it possible to generate the servers public key automatically?
also for server listen port and public IP,

```
The next steps will ask to provide a private address and a name for each client, one at a time.
address of a client (do NOT include /32):
???????    it skipped right over it. ????????????
Provide the name of the client
???????? It did not let me enter a client name, it skipped right over it. ???????????
```
```
NOTE: You need to disable the server WireGuard interface before changing the config.
how can I disable the wire guard interface when I'm the process of adding a new user??

```

**Comment by SirToffski** [comment]
@broros

1. Yep, done! Auto-generating server pub key has been implemented in [this commit ](https://github.com/SirToffski/WireGuard-Ligase/commit/eb55490a43646b392338a30b783f369b094f360e#diff-6adfa3100b4c7e52640cc4e295098532)
2. Regarding skipping over the - I believe this had been fixed in [this commit](https://github.com/SirToffski/WireGuard-Ligase/commit/6636e7cb45c957cae92a35dc60db57b0f6b15361).
3. Added an option to check if there is an active WG interface and offer to disable it - before the script will add the client info to the server config - [this commit ](https://github.com/SirToffski/WireGuard-Ligase/commit/eb55490a43646b392338a30b783f369b094f360e#diff-6adfa3100b4c7e52640cc4e295098532).

**Comment by SirToffski** [comment]
Just pushed a commit to fix the "skip-over issues" - update the repo with `git pull` or simply clone the entire repository again.

Cheers,

**Comment by SirToffski** [comment]
I’ll work on adding an option to the script to check if there is an active WG interface and to offer an option to disable it before adding clients.

**Comment by SirToffski** [comment]
> there are a couple of problems when adding a new user, nothing is automated..
> 
> when generating new clients # 3, is it possible to generate the servers public key automatically?
> also for server listen port and public IP,
> 
> ```
> The next steps will ask to provide a private address and a name for each client, one at a time.
> address of a client (do NOT include /32):
> ???????    it skipped right over it. ????????????
> Provide the name of the client
> ???????? It did not let me enter a client name, it skipped right over it. ???????????
> ```
> 
> ```
> NOTE: You need to disable the server WireGuard interface before changing the config.
> how can I disable the wire guard interface when I'm the process of adding a new user??
> ```



> I’ll work on adding an option to the script to check if there is an active WG interface and to offer an option to disable it before adding clients.
