### ISSUE TITLE
client_config.sh should get public key/ip from existing config

### ISSUE THREAD

**Issue by kovetskiy** [SirToffski/WireGuard-Ligase#7]
Hi. Thanks for open sourcing scripts, it's really useful.

But the client_config.sh should get public key/ip from existing configs instead of asking for user input, it's quite strange to type it everytime when you add a client. Maybe it should ask for user input (or read argument) for the name of device (like wg0) and then read it from /etc/wireguard/wg0.conf

**Comment by SirToffski** [comment]
Hi - makes sense. My original reservation to add this was because I don't always run the script to add client from the same machine that hosts the server - though most of the times I would.

Another difficulty - the server config file `/etc/wireguard/wg0.conf` for example - would not have server public address or server public key in it - if you look at the file - it'll have server private address and server public key only.

So there are a couple of options. One which I am thinking makes the most sense is for the script to get the server ListenPort from the server config .e.g `/etc/wireguard/wg0.conf`. For public address I could re-use the same logic as in other scripts: `check_pub_ip=$(curl -s https://checkip.amazonaws.com)`. This will work if the script is run on the same machine that's hosting the server.

For the server public key - I believe one could generate the public key from a private one (but not vice versa). I'd have to check.

Overall - I like all of your suggestions. The client_config part of the script has definitely been the most neglected one - time to show it some love.

**Comment by SirToffski** [comment]
> Hi. Thanks for open sourcing scripts, it's really useful.
> 
> But the client_config.sh should get public key/ip from existing configs instead of asking for user input, it's quite strange to type it everytime when you add a client. Maybe it should ask for user input (or read argument) for the name of device (like wg0) and then read it from /etc/wireguard/wg0.conf

@kovetskiy
Check out [this commit](https://github.com/SirToffski/WireGuard-Ligase/commit/eb55490a43646b392338a30b783f369b094f360e#diff-6adfa3100b4c7e52640cc4e295098532) - I think it implements your suggestions.

The logic is something like:
1) Ask if the script is running on the same machine the server is on
2) If yes, check files in `/etc/wireguard/*.conf` and ask user if any of those files are the current server config
3) If it is, convert the private key from that config to a public key, also get the listen port from it
4) Use `wg | grep "interface" | awk '{print $2}'` - if output is not empty - there's an active server instance
  4.1) Offer to disable the server to add the config
  4.2) If yes, use `wg-quick down` to disable the config
